spring:
  profiles:
    active: dev
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
server:
  port: 8081
sample:
  value: default
