spring:
  profiles:
    active: dev
  #    datasource:
  #      driver-class-name: org.h2.Driver
  #      url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
  #      username: sa
  #      password: 1028
server:
  port: 8081

sample:
  value: default
